// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gydnxsdlbokgnaugrbhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZG54c2RsYm9rZ25hdWdyYmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjExMjQsImV4cCI6MjA2MDgzNzEyNH0.tyiXFbjrzVy9oWKsYM9yF5zYk9MvRy3A3znBoh9p9Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Enable automatic session persistence
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Store session in localStorage with custom key
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'carebow-auth-v2',
    // Flow type for better security
    flowType: 'pkce',
  },
  // Global configuration
  global: {
    headers: {
      'X-Client-Info': 'carebow-web-app',
    },
  },
  // Real-time configuration
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});